In [1]:
import torch

## Tensor addition simple

In [9]:
x = torch.tensor([[0.6, 0.98], [0.37, 0.45]])
y = torch.tensor([[0.58, 0.23], [0.11, 0.07]])

In [4]:
x.shape

torch.Size([2, 2])

In [7]:
x

tensor([[0.6000, 0.9800],
        [0.3700, 0.4500]])

In [10]:
y.shape

torch.Size([2, 2])

In [11]:
x + y

tensor([[1.1800, 1.2100],
        [0.4800, 0.5200]])

In [13]:
0.98 + 0.23

1.21

## Tensor addition with different dimensions

In [14]:
x = torch.rand(2, 1, 3, 3)
y = torch.rand(1, 3, 1)

In [19]:
x

tensor([[[[0.8920, 0.4217, 0.0935],
          [0.5344, 0.5840, 0.1415],
          [0.7096, 0.9402, 0.5615]]],


        [[[0.5587, 0.8196, 0.9880],
          [0.5417, 0.3123, 0.5779],
          [0.5303, 0.1155, 0.6764]]]])

In [46]:
x[0][0][0][0].item()

0.8919512033462524

<b>Rule: </b> <br>If tensors have a different number of dimensions, the tensor with fewer dimensions is padded with ones on the left side until it matches the number of dimensions of the larger tensor.

y shape: (1, 3, 1) → (1, 1, 3, 1)

In [47]:
y

tensor([[[0.5479],
         [0.0342],
         [0.0426]]])

In [58]:
y[0][0][0]

tensor(0.5479)

<b><h2>Broadcast Rule - Dimension Compatibility </b>
PyTorch now checks each dimension from right to left to determine if broadcasting can occur:

<h3>4th Dimension (rightmost):</h3>

x: 3<br>
y: 1
<br>Result: These dimensions are compatible because 1 can be broadcasted to 3. Tensor y will be expanded to have a size of 3 in this dimension.<br>
<br><h3>3rd Dimension:</h3>

x: 3<br>
y: 3<br>
Result: These dimensions are already equal, so no broadcasting is needed.<br><br>
<h3>2nd Dimension:</h3>

x: 1<br>
y: 1<br>
Result: These dimensions are equal, so no broadcasting is needed.<br><br>
<h3>1st Dimension (leftmost):</h3>

x: 2<br>
y: 1<br>
Result: The dimension 1 in y can be broadcasted to match the dimension 2 in x.
<br><br><h3>At this point, the shape of y has been broadcasted from (1, 1, 3, 1) to (2, 1, 3, 3) to match the shape of x.

In [59]:
x = torch.tensor([[[[1.0, 2.0, 3.0],
                    [4.0, 5.0, 6.0],
                    [7.0, 8.0, 9.0]]],

                  [[[10.0, 11.0, 12.0],
                    [13.0, 14.0, 15.0],
                    [16.0, 17.0, 18.0]]]])

y = torch.tensor([[[[0.1], [0.2], [0.3]]]])

# Perform addition
z = x + y

print(z)


tensor([[[[ 1.1000,  2.1000,  3.1000],
          [ 4.2000,  5.2000,  6.2000],
          [ 7.3000,  8.3000,  9.3000]]],


        [[[10.1000, 11.1000, 12.1000],
          [13.2000, 14.2000, 15.2000],
          [16.3000, 17.3000, 18.3000]]]])


In [77]:
z[0, 0, 2]

tensor([7.3000, 8.3000, 9.3000])

In [76]:
z[0][0][2]

tensor([7.3000, 8.3000, 9.3000])